name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      description: Which modloader does this apply to?
      options:
        - Fabric
        - Forge
        - Both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or examples.
    validations:
      required: false